CREATE DATABASE yeticave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE yeticave;
CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(128) NOT NULL UNIQUE,
	password VARCHAR(60) NOT NULL,
	dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	name VARCHAR(50) NOT NULL,
	contacts VARCHAR(350) NOT NULL,
	avatar TINYTEXT
);

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(128),
	class VARCHAR(128)
);

CREATE TABLE lot (
  id INT AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	name VARCHAR(128),
	description TEXT,
	FULLTEXT KEY `ft1`(`name`,`description`),
	image TINYTEXT,
	start_price INT,
	dt_close TIMESTAMP,
	step_price INT,
	users_id INT,
	win_id INT,
	categories_id INT
);

CREATE TABLE rate (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	amount INT,
	users_id INT,
	lot_id INT
);
